### ISSUE TITLE
Add support for updating a conversation

### ISSUE THREAD

**Issue by darre1** [Vonage/vonage-php-sdk-core#232]
Hi

Is there a development plan/schedule for the new conversation API?

I am using the laravel PHP client, and you can create a conversation through and fetch one too, but it doesn't look like you can update a conversation via the PHP client yet.

Here is the API documentation to the endpoint itself: https://developer.nexmo.com/api/conversation#replaceConversation

**Comment by darre1** [comment]
PS: Looks like you can't delete a conversation via the laravel package either...

**Comment by dragonmantank** [comment]
Hello! Since the product is still currently in Beta, we have no official support for it at the SDK level. In fact, the v3.0.0 release will be removing what support we have for Conversations as the shipped code is not 100% up-to-date anyway, as you can see. The Conversation code currently in the SDK was for a very early version to help support some additional Voice functionality that has now wholly moved to Conversations, and is better exposed through the Voice layer.

We are looking at ways to help provide better support for our beta products directly in our SDKs. For the moment, you can generate a JWT (https://developer.nexmo.com/conversation/guides/jwt-acl) and craft a PSR-7 compatible Request object and send it through `$client->send()` to help cut down on boilerplate. 

I will leave this issue open though and update if there are any changes.

**Comment by SecondeJK** [comment]
Conversation has been removed from the API as of v3. I expect a new implementation will be written by me when we are ready to generally release this product.
