### ISSUE TITLE
SMS Throttle Bug

### ISSUE THREAD

**Issue by abelzx** [Vonage/vonage-php-sdk-core#282]
What is the purpose of these lines?

https://github.com/Vonage/vonage-php-sdk-core/blob/7cfa39414ffb0529ee05d0f4f22225f43cc72ef6/src/SMS/ExceptionErrorHandler.php#L59-L61

In the below case, the script will sleep for 31 seconds and is causing SMS send to timeout (when script max execution time is set to let's say 30 seconds) as it picks the first digits, add 1 and sleep.

https://github.com/Vonage/vonage-php-sdk-core/blob/7cfa39414ffb0529ee05d0f4f22225f43cc72ef6/src/SMS/Client.php#L50-L54

However, sleeping for 1 second is always enough as the interval is always 1 second. Here's an example for exceeded max MT

```
{
    "message-count": "1",
    "messages": [
        {
            "status": "1",
            "error-text": "Exceeded maximum MT throughput[ MAX [ 30 ] INTERVAL [ 1000 ] COUNT [ 30 ] LAST INT-START [ 1617784922564 ] TIME_SINCE_LAST_INTERVAL_START [ 529 ]  ] "
        }
    ]
}
```

The MAX [30] is the MAX allowed MT throughput (API requests), if we want to sleep for the minimum amount of time we will have to use usleep and set the timeout (1000-529) in milli/microseconds.

**Comment by dragonmantank** [comment]
You are correct, this looks like a bug due to unexpected error text being returned.

The intention for the code is to sleep for X seconds, as provided by the API. Most countries do not allow you to hit the actual API throttle limit of (normally) 30 requests a second, so SMS throttles long before your API request limit. The error message is supposed to return the number of seconds to sleep for in the format of `Throughput ate Exceeded - please wait [ 2 ] and retry` or a non-deterministic amount (`Throughput Rate Exceeded - please wait and retry`).

The error message you received however is not what is expected, but the regex is loose enough to capture that `30`.

I'll get a fix out for this ASAP.

**Comment by abelzx** [comment]
Hey Chris, thanks for getting back.

Just checking the error message you mentioned, I think this is only for US/CA where we have throttle per US/CA LVN as sender. However, the returned number seems to return in milliseconds, not seconds. Here is what I got when sending more than the LVN limit `Throughput Rate Exceeded - please wait [ 702 ] and retry`.

**Comment by dragonmantank** [comment]
This is going out as 2.9.1 here in just a bit!
