### ISSUE TITLE
ISSUE? PHP 8.1 Serializable interface deprecated

### ISSUE THREAD

**Issue by kingcoen** [Vonage/vonage-php-sdk-core#324]
## Expected Behavior
A user attempts to verify the phone number, then an error is thrown. 

## Current Behavior
Getting errors on live environment

## Possible Solution
Implement __serialize() and __unserialize(). 

## Your Environment

* Version used: PHP 8.1

**Comment by SecondeJK** [comment]
Hi @kingcoen 
The serialize and unserialize methods on entities are marked as deprecated or have already been removed. This is a design decision, especially since unserialize is a notorious PHP Security risk. (https://riptutorial.com/php/example/14674/security-issues-with-unserialize)

Could you give some more informations please? I need to know what error is thrown to make sure it's not an unintended side effect or behaviour change within PHP 8.1

**Comment by kingcoen** [comment]
Hi @SecondeJK 
This is the full error Im getting from our NewRelic stack trace. 

Error: Vonage\Verify\Verification implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

**Comment by SecondeJK** [comment]
Fixed by #326
