### ISSUE TITLE
[5.x] Remove vonage/nexmo-bridge dependency, make it optional

### ISSUE THREAD

**Issue by ankurk91** [Vonage/vonage-php-sdk-core#398]
Hi,

It has been ~3 years since this PR
https://github.com/Vonage/vonage-php-sdk-core/pull/244

I believe most developers must have migrated their code to have `Vonage` namespace.

Can we get rid of `vonage/nexmo-bridge ` dependency from core?
You can plan to do this in next major version and ask developers to install if required.

This dependency is consuming ~10 ms on each request, We did profiling of our Laravel project.

**Comment by SecondeJK** [comment]
We don't actually support anything under the Nexmo namespace anymore, so yes it does make sense to remove it.

**Comment by ankurk91** [comment]
Would you accept a PR?

**Comment by SecondeJK** [comment]
OK, I'm going to close this -for now- because I cannot just release it as it's a BC break. I've marked this as a task to be done when v5.0 is released (which doesn't have a schedule right now) which could be into next year. I've already done two major releases in the past year and a half to slowly chop out all the deprecations, so this will be part of the next iteration.

Thank you for pointing this out :)
