### ISSUE TITLE
Request the interface to send dtmf, and the interface returns not found

### ISSUE THREAD

**Issue by m7yun** [Vonage/vonage-php-sdk-core#451]
<img width="1032" alt="image" src="https://github.com/Vonage/vonage-php-sdk-core/assets/99463715/e7c95b56-3441-4562-ac75-d9c83eb29f51">

**Comment by SecondeJK** [comment]
Hi,
This isn't an issue with the PHP SDK, it's the API telling you that it cannot find the call ID you've specified. Have a look at the API docs here for how to send the request:
https://developer.vonage.com/en/api/voice#updateCall

It also looks like you're posting something like a mixture of the call UUID and the Conversation ID so that's probably where it's erroring.
